---
- hosts: test-servers
  become: true
  vars:
     ansible_become_pass: vagrant
  tasks:
   - name : install nginx
     package: pkg=nginx state=installed
     notify:
     - start nginx
  
  handlers:
   - name: start nginx
     service: name=nginx state=started
  
