server:
  port: 7000
spring:
  application:
    name: idptest
  datasource:
    url: jdbc:h2:mem:idptest
    username: developer
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true